### ISSUE TITLE
fullPage.js variant app unable to navigate

### ISSUE THREAD

**Issue by rpodcast** [JohnCoene/fullPage#3]
I'm currently using `fullPage` to power my upcoming `rstudio::conf` poster 😄 .  I was hoping to use the `fullPage.js` variant, but I'm unable to navigate to pages past the first page.  This can be seen in the deployed [demo app](https://shiny.john-coene.com/fullPage/) as well.   At least the `pagePiling.js` variant works, although it doesn't let me hide the navigation bar at top (I will have a lot of pages in my app).  Any tricks I can do to fix the issue?

**Comment by JohnCoene** [comment]
Woah, couldn't be happier to hear this!

Thanks for submitting this issue, it completely escaped that the whole thing was broken. I have just pushed a fix. The [demo app](https://shiny.john-coene.com/fullPage/) now works.

Could you please reinstall from Github and let me know if that works for you?

```r
# install.packages("remotes")
remotes::install_github("RinteRface/fullPage")
```

**Comment by JohnCoene** [comment]
You can leave the `menu` argument empty (defaults to `NULL`) to not have the navigation at the top.

**Comment by rpodcast** [comment]
Wow, easily the fastest fix to one of my issues!  Everything works perfect now.  Using the `fullPage` version works better for this because I want to have a bit of "nested" navigation within the broader categories.  Thanks so much!  I'll share the finished version when it's complete 👍

**Comment by JohnCoene** [comment]
Don't get your hopes up, there's probably more :smile: Please feel free to open any more issue you might run into and thank you for using the package.
